version: '2'
services:
    web:
        build: .
        restart: always
        
        ports:
            - "3001:3001"
        volumes:
            .:usr/src/app/db
        
        environment:   
        RACK_ENV: development
     

services:
  web:
    restart: always
    build: .
    ports:
      - "3000:3000"

      postgresd:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=dbuser
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=accesscontroldb

       redis:
            container_name: redis
            image: redis
            volumes:
              - ../data/redis:/data
            restart: always