  
apiVersion: v1
kind: Service
metadata:
  name: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
  
  
  
  labels:
    app: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
    
    
    
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
  
  
  
  labels:
    app: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
 
    
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
      
      
      
  template:
    metadata:
      labels:
        app: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
  
        
        
    spec:
      containers:
      - name: ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui
     
      
      
        image: HannachiNada/ECE-DevOps-project-SI1-Hannachi-Nada---Laroussi-Ilhem---saad-Hasnaoui:latest
        ports:
        - containerPort: 8000